import type { ProfitabilitySettings } from '../components/ProfitabilitySettingsPage';

const baseSettings: Omit<ProfitabilitySettings, 'otherFixed'> = {
    mpg: 0,
    fuelPrice: 0,
    maintenanceDollars: 0,
    maintenanceMiles: 0,
    monthlyFixedBundle: 0,
    tiresDollars: 0,
    tiresMiles: 0,
    maintenanceDollarsDetailed: 0,
    maintenanceMilesDetailed: 0,
    oilChangeDollars: 0,
    oilChangeMiles: 0,
    defFluidDollars: 0,
    defFluidMiles: 0,
    tollsDollars: 0,
    tollsMiles: 0,
    truckPayment: 0,
    truckPaymentPeriod: 1,
    truckPaymentUnit: 'month',
    trailerPayment: 0,
    trailerPaymentPeriod: 1,
    trailerPaymentUnit: 'month',
    insurance: 0,
    insurancePeriod: 1,
    insuranceUnit: 'month',
    permits: 0,
    permitsPeriod: 1,
    permitsUnit: 'year',
    eldSubscription: 0,
    eldSubscriptionPeriod: 1,
    eldSubscriptionUnit: 'month',
    phoneInternet: 0,
    phoneInternetPeriod: 1,
    phoneInternetUnit: 'month',
    parking: 0,
    parkingPeriod: 1,
    parkingUnit: 'month',
    softwareTools: 0,
    softwareToolsPeriod: 1,
    softwareToolsUnit: 'month',
    marginCents: 0,
    marginPercent: 0,
    useWhicheverGreater: true,
    useRealTimeFuel: false,
    useProMode: false,
};

export const createEmptyProfitabilitySettings = (): ProfitabilitySettings => ({
    ...baseSettings,
    otherFixed: [],
});
